# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- master

pool:
  vmImage: 'ubuntu-latest'

steps:
- task: Docker@2
  inputs:
    containerRegistry: 'perceptilabs'
    command: 'login'
    addPipelineData: false

- task: Bash@3
  env:
    QUAY_AUTH_TOKEN: $(QUAY_AUTH_TOKEN)
  inputs:
    targetType: 'inline'
    script: |
      docker login $REGISTRY_URL -u $USERNAME -p $PASSWORD
      make publish
  displayName: Log in to the public registry and push the images
