---
- name: Deploy Perceptilabs backend micro service (core)
  k8s:
    state: present
    definition: "{{ lookup('template', 'core.yaml.j2') }}"

- name: Deploy Perceptilabs frontend micro service
  k8s:
    state: present
    definition: "{{ lookup('template', 'frontend.yaml.j2') }}"