---
- name: Deploy PerceptiLabs API microservice (rygg)
  k8s:
    state: present
    definition: "{{ lookup('template', 'rygg.yaml.j2') }}"

- name: Deploy PerceptiLabs ML microservice (core)
  k8s:
    state: present
    definition: "{{ lookup('template', 'core.yaml.j2') }}"

- name: Deploy PerceptiLabs frontend microservice
  k8s:
    state: present
    definition: "{{ lookup('template', 'frontend.yaml.j2') }}"
