apiVersion: perceptilabs.com/v1alpha1
kind: Perceptilabs
metadata:
  name: example-perceptilabs
spec:
  # Add fields here
  # frontendImage: quay.io/tmckayus/perceptilabs-frontend:v5
  # coreImage: quay.io/tmckayus/perceptilabs-core:v5
  # coreGpus: 3
  # corePvc: mydata
