apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  name: perceptilabs.perceptilabs.com
spec:
  group: perceptilabs.com
  names:
    kind: PerceptiLabs
    listKind: PerceptiLabsList
    plural: perceptilabs
    singular: perceptilabs
  scope: Namespaced
  subresources:
    status: {}
  version: v1
  versions:
  - name: v1
    served: true
    storage: true
