apiVersion: apps/v1
kind: Deployment
metadata:
  name: REPLACE_OP
spec:
  replicas: 1
  selector:
    matchLabels:
      name: REPLACE_OP
  template:
    metadata:
      labels:
        name: REPLACE_OP
    spec:
      containers:
        - name: ansible
          command:
          - /usr/local/bin/ao-logs
          - /tmp/ansible-operator/runner
          - stdout
          image: REPLACE_IMAGE
          imagePullPolicy: Always
          volumeMounts:
          - mountPath: /tmp/ansible-operator/runner
            name: runner
            readOnly: true
        - name: operator
          image: REPLACE_IMAGE
          imagePullPolicy: Always
          volumeMounts:
          - mountPath: /tmp/ansible-operator/runner
            name: runner
          env:
            - name: WATCH_NAMESPACE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
            - name: POD_NAME
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
            - name: OPERATOR_NAME
              value: "REPLACE_OP"
            - name: RELATED_IMAGE_FRONTEND_IMAGE
              value: "REPLACE_FRONTEND_IMAGE"
            - name: RELATED_IMAGE_CORE_IMAGE
              value: "REPLACE_CORE_IMAGE"
      serviceAccountName: perceptilabs-operator-sa
      volumes:
        - name: runner
          emptyDir: {}
