kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: perceptilabs-operator
subjects:
- kind: ServiceAccount
  name: perceptilabs-operator
  namespace: p1
roleRef:
  kind: Role
  name: perceptilabs-operator
  apiGroup: rbac.authorization.k8s.io
  namespace: p1
