#!/usr/bin/env bash
set -Eeuo pipefail

# from https://github.com/operator-framework/operator-registry
# TODO: assume opm is in PATH

if [ $# -lt 2 ]; then
  echo missing arguments
  echo USAGE: $0 version operator-repo
  echo Example: $0 0.0.4 quay.io/perceptilabs/perceptilabs-operator
  exit 1
fi

NEWVERSION=$1                                                                            # e.g. 1.0.1
OPERATOR_REPO=$2 # e.g. quay.io/perceptilabs/perceptilabs-operator
BUNDLE_REPO=${OPERATOR_REPO}-bundle
BUNDLE_TAG=${BUNDLE_REPO}:${NEWVERSION}
BUNDLE_DIR_QUAY=$(git rev-parse --show-toplevel)/bundle_quay/${NEWVERSION}
docker build ${BUNDLE_DIR_QUAY} --tag=${BUNDLE_TAG} --no-cache
docker push ${BUNDLE_TAG}
