#!/usr/bin/env bash

if [ -z "${NS}" ]; then echo Missing NS variable; exit 1; fi

oc delete namespace ${NS}

oc delete customresourcedefinitions perceptilabs.perceptilabs.com
oc delete deployment --namespace=openshift-marketplace perceptilabs-operators
oc delete operatorsources --namespace=openshift-marketplace perceptilabs-operators
