#!/usr/bin/env bash

if [ $# -ne 2 ]; then
  echo USAGE: $0 \<namespace\> \<pod pattern\>
  exit 1
fi
NS=$1
POD_PATTERN=$2


if [ -z "${POD_PATTERN}" ]; then
  echo USAGE: $0 \<pattern\>
  exit 1
fi

get_from_oc(){
  GOT=$(oc get pods --namespace=${NS} -o name | grep -i -e "${POD_PATTERN}")
  if [ $? == 0 ]; then
    echo ${GOT} | cut -d/ -f2
    return 0
  fi
  return 1
}

GOT=$(get_from_oc "${POD_PATTERN}")
if [ $? == 0 ]; then
  echo ${GOT}
  exit 0
fi

echo -n "Waiting for pod ..."
GOT=$(get_from_oc "${POD_PATTERN}")
while [ -z "${GOT}" ]; do
  sleep 1
  echo -n .
  GOT=$(get_from_oc "${POD_PATTERN}")
done
echo done
echo ${GOT}
