#!/usr/bin/env bash

USG="USAGE: $0 <namespace> <pod pattern> [-q]"
if [ $# -lt 2 ]; then
  echo ${USG}
  exit 1
fi
NS=$1
POD_PATTERN=$2
QUIET=$3

if [ -z "${POD_PATTERN}" ]; then
  echo ${USG}
  exit 1
fi

get_from_oc(){
  GOT=$(oc get pods --namespace=${NS} -o name | grep -i -e "${POD_PATTERN}")
  if [ $? == 0 ]; then
    echo ${GOT} | cut -d/ -f2
    return 0
  fi
  return 1
}

GOT=$(get_from_oc "${POD_PATTERN}")
if [ $? != 0 ]; then
  echo -n "Waiting for pod matching '${POD_PATTERN}'..."
  GOT=$(get_from_oc "${POD_PATTERN}")
  while [ -z "${GOT}" ]; do
    sleep 1
    echo -n .
    GOT=$(get_from_oc "${POD_PATTERN}")
  done
  echo "done"
fi

if [ "${QUIET}" != "-q" ]; then
  echo ${GOT}
fi
