#!/usr/bin/env bash

if [ $# -lt 2 ]; then
  echo "USAGE: $0 <namespace> <pod pattern> [-q]"
  exit 1
fi

NS=$1
ROUTE_NAME=$2
QUIET=$3

get_from_oc(){
  oc get route --namespace=${NS} ${ROUTE_NAME} -o jsonpath="{.spec.host}" 2>/dev/null
  return $?
}

GOT=$(get_from_oc)
if [ $? != 0 ]; then
  echo -n Waiting for route ...
  GOT=$(get_from_oc)
  while [ $? != 0 ]; do
    sleep 1
    echo -n .
    GOT=$(get_from_oc)
  done
  echo "done"
fi

if [ "${QUIET}" != "-q" ]; then
  echo ${GOT}
fi
