#!/usr/bin/env bash

if [ $# -lt 2 ]; then
  echo "USAGE: $0 <namespace> <pod pattern> [-q]"
  exit 1
fi
NS=$1
POD_PATTERN=$2
QUIET=$3

TOOLS_DIR="$(dirname $0)"
"${TOOLS_DIR}/get_pod" ${NS} "${POD_PATTERN}" -q
POD=$( "${TOOLS_DIR}/get_pod" ${NS} "${POD_PATTERN}" | tail -n 1 )

get_status(){
  oc get pod --namespace=${NS} ${POD} --output=template={{.status.phase}}
}

PHASE=$(get_status)
if [ "${PHASE}" != "Running" ]; then
  echo -n "Waiting for ${POD} to enter 'Running' state ..."
  sleep 1
  PHASE=$(get_status)
  while [ "${PHASE}" != "Running" ]; do
    sleep 1
    echo -n "."
    PHASE=$(get_status)
  done
  echo "done"
fi

if [ "${QUIET}" != "-q" ]; then
  echo ${POD}
fi
