apiVersion: v1
kind: Namespace
metadata:
  name: REPLACE_NAMESPACE
---
apiVersion: operators.coreos.com/v1
kind: OperatorGroup
metadata:
  name: REPLACE_NAMESPACE-operatorgroup
  namespace: REPLACE_NAMESPACE
spec:
  targetNamespaces:
  - REPLACE_NAMESPACE
