kind: StorageClass
apiVersion: storage.k8s.io/v1
metadata:
  name: perceptilabs-example-sc
  annotations:
    description: Example Storage for Perceptilabs
provisioner: kubernetes.io/aws-ebs
parameters:
  fsType: ext4
  type: gp2
reclaimPolicy: Delete
volumeBindingMode: Immediate
---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: perceptilabs-pvc
  namespace: ${NS}
spec:
  storageClassName: perceptilabs-example-sc
  volumeMode: Filesystem
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 50Gi
