kind: PersistentVolume
apiVersion: v1
metadata:
  name: perceptilabs-pv
spec:
  storageClassName: gp2
  capacity:
    storage: 50Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/mnt/data"
---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: perceptilabs-pvc
  namespace: ${NS}
spec:
  storageClassName: gp2
  volumeMode: Filesystem
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 50Gi
