#!/usr/bin/env bash

if [ $# -ne 1 ]; then
  echo USAGE: $0 url version
  exit 1
fi

APP_URL=$1
RC=$(curl -s -o /dev/null -w "%{http_code}" --head ${APP_URL})
if [ "${RC}" != "200" ]; then
  echo "Application repo is not available. HTTP code: ${RC}"
  exit 1
fi
