#!/usr/bin/env bash

if [ $# -lt 1 ]; then
	echo "USAGE: $0 <version>"
	exit 1
fi

VERSION=$1
REDHAT_REGISTRY=scan.connect.redhat.com
FULL_CORE_REPO="ospid-c5106ae3-19d7-4938-8d58-78789f1bf195"
FULL_FE_REPO="ospid-b7e10edb-0d6c-4222-9374-85874f0204a7"
FULL_OP_REPO="ospid-931b24cb-19a8-40a0-91ef-ba57f919ec30"

assert_var(){
  var=$1
  if [ -z "${!var}" ]; then echo "${var} isn't defined. Go to connect.redhat.com to get the value and then export the variable before running this script."
    exit 1
  fi
}
assert_var FULL_CORE_PWD
assert_var FULL_FE_PWD
assert_var FULL_OP_PWD

do_copy(){
	img=$1
	destimg=$2
	repo=$3
	pswd=$4
	src=quay.io/perceptilabs/${img}:${VERSION}
	dest=${REDHAT_REGISTRY}/${repo}/${destimg}:${VERSION}
	docker pull ${src}
	docker tag ${src} ${dest}
	docker login -u unused -p ${pswd} ${REDHAT_REGISTRY}
	echo "Pushing ${dest}"
	docker push ${dest}
}

do_copy frontend-ubi8 frontend ${FULL_FE_REPO} ${FULL_FE_PWD}
do_copy core-ubi7 core ${FULL_CORE_REPO} ${FULL_CORE_PWD}
do_copy perceptilabs-operator perceptilabs-operator ${FULL_OP_REPO} ${FULL_OP_PWD}
