apiVersion: perceptilabs.com/v1alpha1
kind: Perceptilabs
metadata:
  name: example-perceptilabs
  namespace: REPLACE_NAMESPACE
spec:
  coreImage: perceptilabs.azurecr.io/core:latest
  frontendImage: perceptilabs.azurecr.io/frontend:latest
  serviceAccountName: REPLACE_SERVICEACCOUNT_NAME
  namespace: REPLACE_NAMESPACE
  corePvc: perceptilabs-pvc
  coreGpus: 0
