apiVersion: perceptilabs.com/v1alpha1
kind: Perceptilabs
metadata:
  name: example-perceptilabs
  namespace: p1
spec:
  coreImage: perceptilabs.azurecr.io/core:latest
  frontendImage: perceptilabs.azurecr.io/frontend:latest
  namespace: p1
  # coreGpus: 3
  # corePvc: mydata
