#!/usr/bin/env bash

get_pod(){
  sleep 1
  oc get pods --namespace=p1 -o name | grep perceptilabs-operator-
  return $?
}

get_pod_status(){
  sleep 1
  oc get  --namespace=p1 $1 | tail -n 1 | awk '{print $3}'
}

get_logs(){
  sleep 1
  oc logs $1 --namespace=p1 -c operator | grep -i "starting to serve" &>/dev/null
  return $?
}

oc apply -f tools/subscription.yaml
echo -n Waiting for pod to start ...
POD=$(get_pod)
while [ -z ${POD} ]; do
  echo -n .
  POD=$( get_pod )
done
echo done. Pod name is ${POD}

echo Waiting for ${POD} to enter Running state ...
STATUS=$(get_pod_status ${POD})
while [ "${STATUS}" != "Running" ]; do
  echo "   ${STATUS}"
  STATUS=$(get_pod_status ${POD})
done

echo -n Waiting for pod to serve ...
get_logs ${POD}
while [ $? != 0 ]; do
  echo -n .
  get_logs ${POD}
done
echo done

