#!/usr/bin/env bash


if [ $# -lt 2 ]; then
  echo "USAGE: $0 <app name> <version>"
  echo "example: $0 perceptilabs-operator 1.0.3"
  exit 1
fi


APP_NAME=$1
VERSION=$2
DEST_LEAF=${APP_NAME}.${VERSION}
DEST=bundles/${DEST_LEAF}
DEST_ZIP=bundles/${DEST_LEAF}.zip
OLM_CATALOG_DIR=deploy/olm-catalog
APP_DIR=${OLM_CATALOG_DIR}/${APP_NAME}
PACKAGE_FILE=${APP_DIR}/${APP_NAME}.package.yaml
VERSIONED_DIR=${APP_DIR}/${VERSION}
RH_REGISTRY=registry.connect.redhat.com/perceptilabs
OP_REPO="${RH_REGISTRY}/perceptilabs-operator"
FE_REPO="${RH_REGISTRY}/perceptilabs-frontend-1"
CORE_REPO="${RH_REGISTRY}/perceptilabs-core-1"
echo "The names of the containers for the full version are unknown. Using quay.io repos."
# exit 1


rm -rf ${DEST}
mkdir ${DEST}

cp ${PACKAGE_FILE} ${DEST}
cp ${VERSIONED_DIR}/* ${DEST}
pushd ${DEST}
  sed -i "" "s|quay.io/perceptilabs/perceptilabs-operator|${OP_REPO}|g" *.clusterserviceversion.yaml
  sed -i "" "s|quay.io/perceptilabs/frontend-ubi8|${FE_REPO}|g" *.clusterserviceversion.yaml
  sed -i "" "s|quay.io/perceptilabs/core-ubi7|${CORE_REPO}|g" *.clusterserviceversion.yaml
  zip -q temp.zip *
  mv temp.zip ../${DEST_LEAF}.zip
popd
rm -rf ${DEST}
